# Generated by Django 5.0.7 on 2024-08-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Artist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
