# Generated by Django 5.0.7 on 2024-08-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_album_table_alter_artist_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
    ]
