# Generated by Django 5.0.7 on 2024-08-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_album_table_alter_artist_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='creared_at',
            new_name='created_at',
        ),
    ]
