# Generated by Django 5.0.7 on 2024-08-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_creared_at_artist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='album-img/<function SaveMediaFiles.image_save at 0x00000221FFBECCC0>'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='song-img/<function SaveMediaFiles.image_save at 0x00000221FFBECCC0>'),
        ),
    ]
